FROM cmd:v1
EXPOSE 80/tcp



## EXPOSE will just gives the information of the port the container is running.
## EXPOSE will not chage any the ports just provided information
## docker inspect <Image_ID> it gives the information of the image there also we can see the port.