FROM cmd:v1
EXPOSE 80/tcp



##EXPOSE will jsut gives the information of the port the container is running.
## docker inspect <Image_ID> it gives the information of the image there also we can see the port.