FROM almalinux:9
ADD https://raw.githubusercontent.com/naginenihari/DevSecOps-Notes/refs/heads/main/ansible%20new%20server.txt /tmp/DevSecOps.txt
#ADD sample-2.tar /tmp/
ADD dockerfiles-main.zip /tmp/
CMD ["sleep","150"]
