FROM almalinux:9
ENV course="docker"\
    trainer="Siva"\
    duration="20hrs"
CMD ["sleep","100"]



## Developers can use this environmnet variables inside there code.
## Login to the container and run "env" we can see the ENV variabeles.